[workspace]
resolver = "3"
members = ["apps/juto"]
default-members = ["apps/juto"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
gpui = { version = "=0.2.2", default-features = false, features = ["x11", "wayland"] }

# Favor iteration speed over optimized application/dependency code.
[profile.dev]
opt-level = 0
debug = 1
incremental = true

[profile.test]
opt-level = 0
debug = 1
incremental = true
